project:
  type: website
  output-dir: docs

website:
  title: R, DOT, and TikZ code to plot DAGs and SWIGs for Mendelian randomization analyses
  link-external-icon: true
  repo-url: https://github.com/remlapmot/mrdags
  repo-actions: source
  repo-branch: master
  site-url: https://remlapmot.github.io/mrdags/

format:
  html:
    toc: true
    link-external-icon: true
    format:
    toc-depth: 4
